### ISSUE TITLE
[suggest] fix xPlayer error

### ISSUE THREAD

**Issue by xenfovn** [Musiker15/esx_armor#3]
using "skinchanger:loadClothes" instead of "skinchanger:change"

**Comment by WilderMO** [comment]
What version of "skinchanger" do you use?

**Comment by Musiker15** [comment]
skinchanger:change work for me with esx 1.2 version

**Comment by WilderMO** [comment]
yes. thats why Im asking.

**Comment by xenfovn** [comment]
my file https://cdn.discordapp.com/attachments/933689510062080010/943527077594927114/skinchanger.rar

**Comment by Musiker15** [comment]
Should be fixed now
